/*
 * Copyright 2023 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_IMX8QXP_PINCTRL_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_IMX8QXP_PINCTRL_H_

/* values for pad field */
#define SC_P_SAI1_RXD 86
#define SC_P_SAI1_RXC 87
#define SC_P_SAI1_RXFS 88
#define SC_P_SPI0_CS1 96
#define SC_P_UART2_TX 113
#define SC_P_UART2_RX 114

/* mux values */
#define IMX8QXP_DMA_LPUART2_RX_UART2_RX 0
#define IMX8QXP_DMA_LPUART2_TX_UART2_TX 0
#define IMX8QXP_ADMA_SAI1_TXFS_SAI1_RXFS 1
#define IMX8QXP_ADMA_SAI1_RXD_SAI1_RXD 0
#define IMX8QXP_ADMA_SAI1_TXC_SAI1_RXC 1
#define IMX8QXP_ADMA_SAI1_TXD_SPI0_CS1 2

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_IMX8QXP_PINCTRL_H_ */
