# Copyright (c) 2022 Dhruva Gole <goledhruva@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# NOTE: This is created to be used for CI/CD workflow. So use it only
# if you are in the zephyrproject directory or else things may break.

manifest:
  self:
    path: modules/lib/ArduinoCore-zephyr

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: arduino
      url-base: https://github.com/arduino
    - name: facchinm
      url-base: https://github.com/facchinm
    - name: pillo79
      url-base: https://github.com/pillo79

  projects:
    - name: zephyr
      remote: arduino
      revision: zephyr-arduino-20250520
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_nordic
          - hal_ti
          - hal_ambiq
          - hal_espressif
          - hal_infineon
          - hal_intel
          - hal_nxp
          - hal_stm32
          - hal_xtensa
          - hal_nordic
          - hal_renesas
          - hal_adi
          - hal_atmel
          - hal_rpi_pico
          - hal_silabs
          - littlefs
          - tinycrypt
          - mbedtls
          - segger
          - thrift
          - mcuboot
          - lvgl
    - name: ArduinoCore-API
      path: modules/lib/ArduinoCore-API
      revision: master
      url: https://github.com/arduino/ArduinoCore-API
