# Copyright (c) 2022 Dhruva Gole <goledhruva@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# NOTE: This is created to be used for CI/CD workflow. So use it only
# if you are in the zephyrproject directory or else things may break.

manifest:
  self:
    path: modules/lib/ArduinoCore-zephyr

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: arduino
      url-base: https://github.com/arduino
    - name: facchinm
      url-base: https://github.com/facchinm
    - name: pillo79
      url-base: https://github.com/pillo79

  projects:
    - name: zephyr
      remote: arduino
      revision: zephyr-arduino-20250520
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - littlefs
          - tinycrypt
          - mbedtls
          - segger
          - thrift
          - mcuboot
          - lvgl
        path-allowlist:
          - modules/hal/*

        # The actual list of enabled HALs is set by extra/bootstrap.sh via
        # the 'manifest.project-filter' config. Enable all Zephyr HALs with:
        #
        #   west config -d manifest.project-filter

    - name: ArduinoCore-API
      path: modules/lib/ArduinoCore-API
      revision: master
      url: https://github.com/arduino/ArduinoCore-API
