#!/bin/bash

# Copyright Arduino s.r.l. and/or one of its affiliated companies.
# SPDX-License-Identifier: Apache-2.0

BASE_DIR=$(readlink -f $(dirname $0)/..)
OUTPUT_FILE=${1:-$BASE_DIR/.github/dependabot.yml}

dependabot_rule_for() {
	local tool=$(basename $1)
	cat << EOF

  - package-ecosystem: "gomod"
    directory: "/tools/$tool"
    schedule:
      interval: "weekly"
    groups:
      $tool:
        patterns:
          - "*"
EOF
}

cat << EOF
# Autogenerated by extra/ci_dependabot_config.sh - DO NOT EDIT"

version: 2
updates:
EOF
for tool in $(find $BASE_DIR/tools -name "go.mod" -exec dirname '{}' \; | sort); do
	dependabot_rule_for $tool
done > $OUTPUT_FILE
