#!/usr/bin/env python

# Copyright (c) Arduino s.r.l. and/or its affiliated companies
# SPDX-License-Identifier: Apache-2.0

# Generate the SPDX documents describing the core package contents for each
# given variant, from a core package archive created by extra/package_core.sh.
# Each is written next to the variant's SPDX documents generated by
# 'west spdx' (see extra/build.sh), as <spdx-dir>/<variant>/core.spdx for
# SPDX 2.x or core.jsonld for SPDX 3.0.
# The version is selected with --spdx-version or the SPDX_VERSION environment
# variable, and must match the one used by extra/build.sh.
#
# The core sources and the ArduinoCore-API are listed file by file; the
# variant firmware and LLEXT EDK are summarized in one package each, linked to
# the loader SPDX documents in <spdx-dir>/<variant>/loader/. With sysbuild, the
# firmware also has the sources of the other images (e.g. MCUboot, in
# <spdx-dir>/<variant>/mcuboot/) as prerequisites. Files belonging to other
# variants, if any are in the archive, are ignored.
#
# For SPDX 3, the SPDX License List licenses imported by the variant documents
# are downloaded in their SPDX 3 form to <spdx-dir>/<variant>/licenses/, so
# that the document set is self-contained, and the core document points to
# them; --no-license-download skips this.
#
# Uses the 'zspdx' library from Zephyr, located via $ZEPHYR_BASE or the
# current west workspace.

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
import uuid

import yaml

REPO_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
CORE_ROOT = "ArduinoCore-zephyr"
CORE_URL = "https://github.com/arduino/ArduinoCore-zephyr"
SUPPLIER = "Arduino"
API_DIR = "cores/arduino/api/"
API_LICENSE = "LGPL-2.1-or-later"

# SPDX License List: current version, and the SPDX 3 definition of each license
LICENSE_LIST_URL = "https://spdx.org/licenses/licenses.json"
LICENSE_DATA_URL = (
    "https://raw.githubusercontent.com/spdx/license-list-data/{tag}/SPDXv3/v3jsonld/{id}.json"
)
LICENSES_DIR = "licenses"

# relationship of a file copied from another one (SPDX 3 copiedTo, reversed)
COPY_OF = "COPY_OF"


def find_zephyr_base():
    zephyr_base = os.environ.get("ZEPHYR_BASE")
    if not zephyr_base:
        try:
            topdir = subprocess.check_output(["west", "topdir"], text=True, stderr=subprocess.DEVNULL)
            zephyr_base = os.path.join(topdir.strip(), "zephyr")
        except (OSError, subprocess.CalledProcessError):
            pass
    if not zephyr_base or not os.path.isdir(os.path.join(zephyr_base, "scripts", "pylib", "zspdx")):
        sys.exit("zspdx not found: set ZEPHYR_BASE or run from a west workspace")
    return zephyr_base


sys.path.insert(0, os.path.join(find_zephyr_base(), "scripts", "pylib"))

from zspdx.model import (  # noqa: E402
    ComponentPurpose,
    RelationshipType,
    SBOMComponent,
    SBOMDocument,
    SBOMFile,
    SBOMGraph,
)
from zspdx.scanner import (  # noqa: E402
    ScannerConfig,
    get_component_licenses,
    normalize_expression,
    scan_sbom_graph,
)
from zspdx.serializers.spdx2 import SPDX2Serializer  # noqa: E402
from zspdx.util import get_hashes  # noqa: E402
from zspdx.version import parse as parse_spdx_version  # noqa: E402

SPDX_VERSIONS = ["2.2", "2.3", "3.0"]


class CoreSerializer2(SPDX2Serializer):
    """Writes only the 'core' document; the other documents in the graph are
    placeholders for the existing loader SPDX documents it refers to."""

    def __init__(self, sbom_graph, spdx_version, external_docs):
        super().__init__(sbom_graph, spdx_version)
        # document name -> (SHA1 of the real file, SPDX ID of the target package)
        self.external_docs = external_docs

    def _generate_ids(self):
        super()._generate_ids()
        for doc_name, (doc_hash, target_id) in self.external_docs.items():
            doc = self.sbom_graph.get_document(doc_name)
            for component in doc.components.values():
                self.component_ids[component.name] = target_id
            self.document_hashes[doc_name] = doc_hash

    def serialize(self, output_dir):
        self._generate_ids()
        doc = self.sbom_graph.get_document("core")
        output_path = os.path.join(output_dir, "core.spdx")
        return self._write_document_first_pass(doc, output_path) and self._write_document_second_pass(
            doc, output_path
        )


def make_spdx3_serializer(sbom_graph, spdx_version, links):
    """SPDX 3 serializer for the 'core' document. Links to the image documents
    are added here to their imported packages, since the Zephyr serializer only
    handles links within its own graph (and leaves build provenance to the
    Build profile)."""
    # imported here, as the SPDX 3 bindings are not needed for SPDX 2.x
    from zspdx.serializers.spdx3 import serializer as spdx3

    class CoreSerializer3(spdx3.SPDX3Serializer):
        def __init__(self):
            super().__init__(sbom_graph, spdx_version)
            # always write full IRIs, as 'west spdx --no-namespace-map' does:
            # the core document links to the image documents, which come from
            # other builds, and prefixed IDs are only expanded by namespaceMap-
            # aware tools, not by JSON-LD consumers
            self.namespace_prefixes = {}

        def _initialize_shared_objects(self):
            first = self.tool is None
            super()._initialize_shared_objects()
            if first:
                self.creator_agent.name = self.tool.name
                version = self.sbom_data.metadata["tool_version"]
                for ext_id in self.tool.externalIdentifier:
                    ext_id.identifier = f"pkg:github/arduino/ArduinoCore-zephyr@{version}"

        def _map_relationship_type(self, rel_type):
            # not mapped by Zephyr, which covers it with the Build profile
            if rel_type == RelationshipType.GENERATED_FROM:
                return spdx3.spdx.RelationshipType.generates, True
            # not in the zspdx model: the local file is a copy of the target
            if rel_type == COPY_OF:
                return spdx3.spdx.RelationshipType.copiedTo, True
            return super()._map_relationship_type(rel_type)

        def _create_documents(self):
            super()._create_documents()
            spdx = spdx3.spdx
            document = self.documents["core"]
            document.name = "ArduinoCore-zephyr"
            imports = {}
            for element, rel_type, ext_id, location, sha256 in links:
                local_id = self._get_element_id(element)
                rel = spdx.Relationship()
                rel._id = self._generate_relationship_id(len(self.relationship_elements))
                rel.relationshipType, reversed_rel = self._map_relationship_type(rel_type)
                rel.from_, rel.to = (ext_id, [local_id]) if reversed_rel else (local_id, [ext_id])
                rel.creationInfo = self.creation_info._id
                self.elements.append(rel)
                self.relationship_elements.append(rel)
                document.element.append(rel)
                imports[ext_id] = (location, sha256)
            for ext_id, (location, sha256) in sorted(imports.items()):
                ext_map = spdx.ExternalMap()
                ext_map.externalSpdxId = ext_id
                ext_map.locationHint = location
                digest = spdx.Hash()
                digest.algorithm = spdx.HashAlgorithm.sha256
                digest.hashValue = sha256
                ext_map.verifiedUsing.append(digest)
                document.import_.append(ext_map)

            # describe the core package through a build SBOM, the root of the
            # document, as SBOM consumers expect
            sbom = spdx.software_Sbom()
            sbom._id = f"{self.sbom_data.namespace_prefix.rstrip('/')}/sboms/core"
            sbom.name = document.name
            sbom.creationInfo = self.creation_info._id
            sbom.software_sbomType.append(spdx.software_SbomType.build)
            sbom.profileConformance.extend(document.profileConformance)
            for name in self.sbom_data.get_document("core").described_components:
                sbom.rootElement.append(self.component_elements[name])
            for element in document.element:
                sbom.element.append(element)
            self.elements.append(sbom)
            document.element.append(sbom)
            document.rootElement = [sbom]

    return CoreSerializer3()


def read_property(path, key):
    with open(path) as f:
        for line in f:
            if line.startswith(f"{key}="):
                return line.split("=", 1)[1].strip()
    return ""


def read_namespace(spdx_path):
    with open(spdx_path) as f:
        for line in f:
            if line.startswith("DocumentNamespace:"):
                return line.split(":", 1)[1].strip()
    return ""


def read_jsonld_elements(jsonld_path):
    """Elements of an SPDX 3 JSON-LD document, as (full spdxId, element)."""
    with open(jsonld_path) as f:
        graph = json.load(f)["@graph"]
    # older Zephyr versions write prefixed IDs, declared in namespaceMap
    prefixes = {}
    for element in graph:
        for ns in element.get("namespaceMap", []):
            prefixes[ns["prefix"]] = ns["namespace"]
    for element in graph:
        if "spdxId" in element:
            prefix, _, rest = element["spdxId"].partition(":")
            yield (prefixes[prefix] + rest if prefix in prefixes else element["spdxId"]), element


def read_jsonld_package_id(jsonld_path, name):
    """Full spdxId of the named package in an SPDX 3 JSON-LD document. Names
    are compared as in SPDX IDs, with '_' replaced by '-'."""
    for spdx_id, element in read_jsonld_elements(jsonld_path):
        if element.get("type") == "software_Package" and element.get("name", "").replace("_", "-") == name:
            return spdx_id
    return None


def link_copies(files, jsonld_path):
    """Links of the files that are exact copies of a file in an SPDX 3
    document, matched by SHA256: (file, COPY_OF, spdxId, location hint, SHA256
    of the document), as for CoreSerializer3."""
    if not os.path.isfile(jsonld_path):
        return []
    by_sha256 = {}
    for spdx_id, element in read_jsonld_elements(jsonld_path):
        if element.get("type") == "software_File":
            for digest in element.get("verifiedUsing", []):
                if digest.get("algorithm") == "sha256":
                    by_sha256[digest["hashValue"]] = spdx_id
    location = "./" + os.path.relpath(jsonld_path, os.path.dirname(os.path.dirname(jsonld_path))).replace(os.sep, "/")
    doc_sha256 = get_hashes(jsonld_path)[1]
    return [
        (f, COPY_OF, by_sha256[f.hashes["SHA256"]], location, doc_sha256)
        for f in files
        if f.hashes.get("SHA256") in by_sha256
    ]


def link_spdx2(graph, links, variant_dir):
    """Add placeholder documents for the image SPDX documents and the
    relationships to them; returns the external document info for
    CoreSerializer2."""
    external_docs = {}
    targets = {}
    for element, rel_type, image, kind, package in links:
        doc_name = f"{image}-{kind}"
        if doc_name not in targets:
            spdx_path = os.path.join(variant_dir, image, f"{kind}.spdx")
            targets[doc_name] = None
            if not os.path.isfile(spdx_path):
                print(f"warning: {spdx_path} not found, not linking", file=sys.stderr)
                continue
            graph.add_document(SBOMDocument(name=doc_name, namespace=read_namespace(spdx_path)))
            targets[doc_name] = SBOMComponent(name=f"{doc_name}-{package}")
            graph.add_component(targets[doc_name], doc_name)
            external_docs[doc_name] = (get_hashes(spdx_path)[0], f"SPDXRef-{package}")
        if targets[doc_name]:
            graph.add_relationship(element, targets[doc_name], rel_type)
    return external_docs


def link_spdx3(links, variant_dir):
    """Resolve the image SPDX 3 documents; returns the links for
    CoreSerializer3 as (element, relationship, external spdxId, location hint,
    sha256)."""
    resolved = []
    targets = {}
    for element, rel_type, image, kind, package in links:
        location = f"./{image}/{kind}.jsonld"
        if (location, package) not in targets:
            jsonld_path = os.path.join(variant_dir, image, f"{kind}.jsonld")
            targets[(location, package)] = None
            if not os.path.isfile(jsonld_path):
                print(f"warning: {jsonld_path} not found, not linking", file=sys.stderr)
                continue
            ext_id = read_jsonld_package_id(jsonld_path, package)
            if not ext_id:
                print(f"warning: no '{package}' package in {jsonld_path}, not linking", file=sys.stderr)
                continue
            targets[(location, package)] = (ext_id, get_hashes(jsonld_path)[1])
        if targets[(location, package)]:
            ext_id, sha256 = targets[(location, package)]
            resolved.append((element, rel_type, ext_id, location, sha256))
    return resolved


def sysbuild_images(variant_dir):
    """Images other than the loader with SPDX documents, as generated by
    extra/build.sh for sysbuild (e.g. 'mcuboot')."""
    if not os.path.isdir(variant_dir):
        return []
    return sorted(
        d for d in os.listdir(variant_dir)
        if d != "loader"
        and any(os.path.isfile(os.path.join(variant_dir, d, f"app.{ext}")) for ext in ("spdx", "jsonld"))
    )


def listed_license_id(spdx_id):
    """License List identifier of an SPDX 3 license IRI, or None."""
    # use the same IRIs as the Zephyr serializer (older ones use https://)
    from zspdx.serializers.spdx3 import serializer as spdx3

    prefix = getattr(spdx3.SPDX3Serializer, "_LISTED_LICENSE_PREFIX", "https://spdx.org/licenses/")
    if spdx_id.startswith(prefix):
        license_id = spdx_id[len(prefix):]
        if re.fullmatch(r"[A-Za-z0-9.+-]+", license_id):
            return license_id
    return None


def jsonld_documents(variant_dir):
    """SPDX 3 documents of a variant: the core one and those of each image."""
    paths = []
    for dirpath, dirnames, filenames in os.walk(variant_dir):
        dirnames[:] = sorted(d for d in dirnames if d != LICENSES_DIR)
        paths += [os.path.join(dirpath, f) for f in sorted(filenames) if f.endswith(".jsonld")]
    return paths


def spdx_documents(graph):
    return [e for e in graph if e.get("type") == "SpdxDocument"]


def download_licenses(variant_dir):
    """Download the SPDX 3 definition of every License List license imported
    by the variant documents to <variant_dir>/licenses/. Returns the license
    identifiers that are available there."""
    license_ids = set()
    for path in jsonld_documents(variant_dir):
        with open(path) as f:
            for doc in spdx_documents(json.load(f)["@graph"]):
                for ext_map in doc.get("import", []):
                    license_id = listed_license_id(ext_map["externalSpdxId"])
                    if license_id:
                        license_ids.add(license_id)

    licenses_dir = os.path.join(variant_dir, LICENSES_DIR)
    shutil.rmtree(licenses_dir, ignore_errors=True)
    if not license_ids:
        return set()

    try:
        with urllib.request.urlopen(LICENSE_LIST_URL, timeout=30) as f:
            tag = "v" + json.load(f)["licenseListVersion"]
    except (OSError, ValueError, KeyError) as e:
        print(f"warning: cannot get the SPDX License List version: {e}", file=sys.stderr)
        return set()

    os.makedirs(licenses_dir)
    available = set()
    for license_id in sorted(license_ids):
        url = LICENSE_DATA_URL.format(tag=tag, id=license_id)
        try:
            with urllib.request.urlopen(url, timeout=30) as f:
                data = f.read()
            json.loads(data)
        except (OSError, ValueError) as e:
            print(f"warning: cannot download {url}: {e}", file=sys.stderr)
            continue
        with open(os.path.join(licenses_dir, f"{license_id}.json"), "wb") as f:
            f.write(data)
        available.add(license_id)
    print(f"Downloaded {len(available)} SPDX License List {tag} licenses to {licenses_dir}")
    return available


def add_license_location_hints(path, available):
    """Point the License List imports of an SPDX 3 document to the local
    license definitions."""
    with open(path) as f:
        data = json.load(f)
    for doc in spdx_documents(data["@graph"]):
        for ext_map in doc.get("import", []):
            license_id = listed_license_id(ext_map["externalSpdxId"])
            if license_id in available:
                ext_map["locationHint"] = f"./{LICENSES_DIR}/{license_id}.json"
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


def shared_variant_dirs():
    """Directories in variants/ shared by all variants, as listed in the
    common package contents."""
    with open(os.path.join(REPO_DIR, "extra", "artifacts", "_common.inc")) as f:
        entries = [line.split("#")[0].strip().rstrip("/") for line in f]
    return {e.split("/", 1)[1] for e in entries if e.startswith("variants/")}


def api_blob_info():
    module_yml = os.path.join(REPO_DIR, "zephyr", "module.yml")
    with open(module_yml) as f:
        meta = yaml.safe_load(f)
    for blob in meta.get("blobs", []):
        if blob.get("path", "").startswith("ArduinoCore-API/"):
            return blob
    return {}


def inherit_unit_licenses(component):
    """Files in a library or variant without licensing info of their own
    (examples, metadata, configuration...) get the license of that unit, when
    all of its tagged files share the same one."""
    units = {}
    for f in component.files.values():
        m = re.match(r"(libraries|variants)/[^/]+/", f.relative_path)
        if m and os.path.basename(f.path) != "LICENSE":
            units.setdefault(m.group(0), []).append(f)

    for unit, files in sorted(units.items()):
        untagged = [f for f in files if f.concluded_license == "NOASSERTION"]
        if not untagged:
            continue
        # only the unit's own files count, not the bundled examples
        licenses = {
            f.concluded_license
            for f in files
            if f.license_info_in_file and not re.match(r"[^/]+/[^/]+/(examples|extras)/", f.relative_path)
        }
        if len(licenses) != 1:
            print(f"warning: no single license for {unit}, {len(untagged)} files left as NOASSERTION", file=sys.stderr)
            continue
        (license,) = licenses
        for f in untagged:
            f.concluded_license = license

    lics_concluded, _ = get_component_licenses(component)
    component.concluded_license = normalize_expression(lics_concluded)


def generate_core(root, variant, args, spdx_version, namespace_prefix):
    """Write the core SPDX document of a variant, from the core package
    extracted to root."""
    graph = SBOMGraph(namespace_prefix=namespace_prefix)
    core_version = read_property(os.path.join(root, "platform.txt"), "version")
    graph.metadata["creator_organization"] = SUPPLIER
    graph.metadata["tool_name"] = "ArduinoCore-zephyr gen_core_spdx"
    graph.metadata["tool_version"] = core_version

    doc = SBOMDocument(name="core", title="ArduinoCore-zephyr")
    graph.add_document(doc)

    core = SBOMComponent(
        name="ArduinoCore-zephyr",
        purpose=ComponentPurpose.SOURCE,
        version=core_version,
        url=CORE_URL,
        base_dir=root,
        supplier=SUPPLIER,
    )
    graph.add_component(core, doc.name)
    doc.add_described_component(core)

    blob = api_blob_info()
    api = SBOMComponent(
        name="ArduinoCore-API",
        purpose=ComponentPurpose.LIBRARY,
        version=str(blob.get("version", "")),
        url=blob.get("url", ""),
        base_dir=root,
        declared_license=API_LICENSE,
        supplier=SUPPLIER,
    )
    if api.version:
        api.add_external_reference(f"pkg:github/arduino/ArduinoCore-API@{api.version}")
    graph.add_component(api, doc.name)
    graph.add_relationship(core, api, RelationshipType.CONTAINS)

    # variant firmware and EDK packages
    variants_dir = os.path.join(root, "variants")
    other_variants = set(os.listdir(variants_dir)) - shared_variant_dirs() - {variant}
    # links to the image documents:
    # (element, relationship, image, document, target package)
    links = []

    fw = SBOMComponent(
        name=f"{variant}-firmware",
        purpose=ComponentPurpose.APPLICATION,
        version=core_version,
        base_dir=root,
        supplier=SUPPLIER,
        comment=f"Loader firmware for {variant}",
    )
    graph.add_component(fw, doc.name)
    graph.add_relationship(core, fw, RelationshipType.CONTAINS)

    edk = SBOMComponent(
        name=f"{variant}-llext-edk",
        purpose=ComponentPurpose.SOURCE,
        version=core_version,
        supplier=SUPPLIER,
        comment=f"LLEXT EDK for {variant}: headers exported from the loader build, with comments stripped",
    )
    graph.add_component(edk, doc.name)
    graph.add_relationship(core, edk, RelationshipType.CONTAINS)
    links.append((edk, RelationshipType.GENERATED_FROM, "loader", "zephyr", "zephyr-sources"))

    # assign each file in the archive to its component
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        rel_dir = os.path.relpath(dirpath, root)
        parts = rel_dir.split(os.sep)
        if len(parts) >= 2 and parts[0] == "variants" and parts[1] in other_variants:
            dirnames.clear()  # another variant
            continue
        if len(parts) >= 3 and parts[0] == "variants" and parts[2] == "llext-edk":
            dirnames.clear()  # summarized in the EDK package
            continue
        for filename in sorted(filenames):
            path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(path, root)
            if rel_path == "REUSE.toml":
                continue  # copied for the scan, not part of the package
            component = core
            if rel_path.startswith(API_DIR):
                component = api
            elif m := re.match(r"firmwares/zephyr-(.+)\.[^.]+$", rel_path):
                if m.group(1) != variant:
                    continue  # another variant
                component = fw
            sbom_file = SBOMFile(path=path)
            graph.add_file(sbom_file, component)
            if component is fw:
                links.append((sbom_file, RelationshipType.GENERATED_FROM, "loader", "app", "app-sources"))

    scan_sbom_graph(ScannerConfig(), graph)
    inherit_unit_licenses(core)

    # the firmware needs the other sysbuild images (e.g. the bootloader);
    # link to their sources, like the firmware files to the loader ones
    output_dir = os.path.join(args.spdx_dir, variant)
    for image in sysbuild_images(output_dir):
        links.append((fw, RelationshipType.HAS_PREREQUISITE, image, "app", "app-sources"))

    os.makedirs(output_dir, exist_ok=True)
    if spdx_version.major == 2:
        serializer = CoreSerializer2(graph, spdx_version, link_spdx2(graph, links, output_dir))
        output = "core.spdx"
    else:
        # the firmware files that are copies of the built loader image
        copies = link_copies(fw.files.values(), os.path.join(output_dir, "loader", "build.jsonld"))
        serializer = make_spdx3_serializer(graph, spdx_version, link_spdx3(links, output_dir) + copies)
        output = "core.jsonld"
    if not serializer.serialize(output_dir):
        sys.exit("failed to write core SPDX document")
    print(f"Wrote {os.path.join(output_dir, output)}")

    if spdx_version.major == 3:
        if args.no_license_download:
            shutil.rmtree(os.path.join(output_dir, LICENSES_DIR), ignore_errors=True)
        else:
            available = download_licenses(output_dir)
            add_license_location_hints(os.path.join(output_dir, output), available)


def main():
    parser = argparse.ArgumentParser(description="Generate the SPDX documents for a core package archive.")
    parser.add_argument("archive", help="core package archive (.tar.bz2)")
    parser.add_argument("spdx_dir", help="SPDX directory, with <variant>/loader/ documents from west spdx")
    parser.add_argument("variants", nargs="+", metavar="variant", help="variant to describe")
    parser.add_argument("-n", "--namespace-prefix", help="namespace prefix")
    parser.add_argument(
        "--spdx-version",
        choices=SPDX_VERSIONS,
        default=os.environ.get("SPDX_VERSION", "3.0"),
        help="SPDX version (default: $SPDX_VERSION or 3.0)",
    )
    parser.add_argument(
        "--no-license-download",
        action="store_true",
        help="SPDX 3: do not download the imported License List licenses",
    )
    args = parser.parse_args()
    if args.spdx_version not in SPDX_VERSIONS:
        parser.error(f"unsupported SPDX version {args.spdx_version}")
    spdx_version = parse_spdx_version(args.spdx_version)

    with tempfile.TemporaryDirectory() as tmpdir:
        with tarfile.open(args.archive) as tar:
            tar.extractall(tmpdir, filter="data")
        root = os.path.join(tmpdir, CORE_ROOT)
        if not os.path.isdir(root):
            sys.exit(f"'{CORE_ROOT}/' not found in {args.archive}")
        for variant in args.variants:
            if not os.path.isdir(os.path.join(root, "variants", variant, "llext-edk")):
                sys.exit(f"variant '{variant}' not found in {args.archive}")

        # annotations for files that cannot carry SPDX tags (not listed)
        shutil.copy(os.path.join(REPO_DIR, "REUSE.toml"), root)

        for variant in args.variants:
            if args.namespace_prefix:
                namespace_prefix = f"{args.namespace_prefix.rstrip('/')}/{variant}"
            else:
                namespace_prefix = f"http://spdx.org/spdxdocs/arduinocore-zephyr-{uuid.uuid4()}"
            generate_core(root, variant, args, spdx_version, namespace_prefix)


if __name__ == "__main__":
    main()
