#!/usr/bin/env python

# Copyright (c) Arduino s.r.l. and/or its affiliated companies
# SPDX-License-Identifier: Apache-2.0

# Generate the SPDX 2.3 documents describing the core package contents for
# each given variant, from a core package archive created by
# extra/package_core.sh. Each is written next to the variant's SPDX documents
# generated by 'west spdx' (see extra/build.sh), as
# <spdx-dir>/<variant>/core.spdx.
#
# The core sources and the ArduinoCore-API are listed file by file; the
# variant firmware and LLEXT EDK are summarized in one package each, linked to
# the loader SPDX documents in <spdx-dir>/<variant>/loader/. With sysbuild, the
# other images shipped in the archive as firmwares/<image>-<variant>.* (e.g.
# MCUboot) get their own package, linked to the image documents in
# <spdx-dir>/<variant>/<image>/, as prerequisites of the firmware. Files belonging
# to other variants, if any are in the archive, are ignored. Firmware files that
# are exact copies of a file of an image build document (e.g. the ELF image) are
# linked to it.
#
# Uses the 'zspdx' library from Zephyr, located via $ZEPHYR_BASE or the
# current west workspace.

import argparse
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.parse
import uuid

import yaml

REPO_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
CORE_ROOT = "ArduinoCore-zephyr"
CORE_URL = "https://github.com/arduino/ArduinoCore-zephyr"
CORE_PURL = "pkg:github/arduino/ArduinoCore-zephyr"
SUPPLIER = "Arduino"
API_DIR = "cores/arduino/api/"
API_LICENSE = "LGPL-2.1-or-later"
SPDX_VERSION = "2.3"


def find_zephyr_base():
    zephyr_base = os.environ.get("ZEPHYR_BASE")
    if not zephyr_base:
        try:
            topdir = subprocess.check_output(["west", "topdir"], text=True, stderr=subprocess.DEVNULL)
            zephyr_base = os.path.join(topdir.strip(), "zephyr")
        except (OSError, subprocess.CalledProcessError):
            pass
    if not zephyr_base or not os.path.isdir(os.path.join(zephyr_base, "scripts", "pylib", "zspdx")):
        sys.exit("zspdx not found: set ZEPHYR_BASE or run from a west workspace")
    return zephyr_base


sys.path.insert(0, os.path.join(find_zephyr_base(), "scripts", "pylib"))

from zspdx.model import (  # noqa: E402
    ComponentPurpose,
    RelationshipType,
    SBOMComponent,
    SBOMDocument,
    SBOMFile,
    SBOMGraph,
)
from zspdx.scanner import (  # noqa: E402
    ScannerConfig,
    get_component_licenses,
    normalize_expression,
    scan_sbom_graph,
)
from zspdx.serializers.spdx2 import SPDX2Serializer  # noqa: E402
from zspdx.util import get_hashes  # noqa: E402
from zspdx.version import parse as parse_spdx_version  # noqa: E402


class CoreSerializer2(SPDX2Serializer):
    """Writes only the 'core' document; the other documents in the graph are
    placeholders for the existing loader SPDX documents it refers to."""

    def __init__(self, sbom_graph, spdx_version, external_docs, copies):
        super().__init__(sbom_graph, spdx_version)
        # document name -> (SHA1 of the real file, SPDX ID of the target package)
        self.external_docs = external_docs
        # file path -> [(document name, SPDX ID of the file it is a copy of)]
        self.copies = copies

    def _generate_ids(self):
        super()._generate_ids()
        for doc_name, (doc_hash, target_id) in self.external_docs.items():
            doc = self.sbom_graph.get_document(doc_name)
            for component in doc.components.values():
                self.component_ids[component.name] = target_id
            self.document_hashes[doc_name] = doc_hash

    def _write_file(self, f, file_obj, doc):
        super()._write_file(f, file_obj, doc)
        # not in the zspdx model
        for doc_name, target_id in self.copies.get(file_obj.path, []):
            f.write(f"Relationship: {self.file_ids[file_obj.path]} COPY_OF {self.document_refs[doc_name]}:{target_id}\n")

    def serialize(self, output_dir):
        self._generate_ids()
        doc = self.sbom_graph.get_document("core")
        output_path = os.path.join(output_dir, "core.spdx")
        return self._write_document_first_pass(doc, output_path) and self._write_document_second_pass(
            doc, output_path
        )


def read_property(path, key):
    with open(path) as f:
        for line in f:
            if line.startswith(f"{key}="):
                return line.split("=", 1)[1].strip()
    return ""


def read_namespace(spdx_path):
    with open(spdx_path) as f:
        for line in f:
            if line.startswith("DocumentNamespace:"):
                return line.split(":", 1)[1].strip()
    return ""


def read_file_ids_by_sha256(spdx_path):
    """SPDX IDs of the files of an SPDX 2 tag-value document, by SHA256."""
    ids, spdx_id, in_file = {}, None, False
    with open(spdx_path) as f:
        for line in f:
            tag, _, value = line.rstrip("\n").partition(": ")
            if tag == "FileName":
                in_file, spdx_id = True, None
            elif tag in ("PackageName", "Relationship"):
                in_file = False
            elif in_file and tag == "SPDXID":
                spdx_id = value
            elif in_file and tag == "FileChecksum" and value.startswith("SHA256: ") and spdx_id:
                ids[value.split(": ", 1)[1]] = spdx_id
    return ids


def link_copies(graph, doc, files, spdx_path, doc_name):
    """Find the files that are exact copies of a file of an SPDX 2 document,
    matched by SHA256, and register that document as external to doc.
    Returns {file path: [(document name, SPDX ID)]} and the external document
    info for CoreSerializer2."""
    if not os.path.isfile(spdx_path):
        return {}, {}
    by_sha256 = read_file_ids_by_sha256(spdx_path)
    copies = {
        f.path: [(doc_name, by_sha256[f.hashes["SHA256"]])]
        for f in files
        if f.hashes.get("SHA256") in by_sha256
    }
    if not copies:
        return {}, {}
    external = SBOMDocument(name=doc_name, namespace=read_namespace(spdx_path))
    graph.add_document(external)
    doc.add_external_document(external)
    return copies, {doc_name: (get_hashes(spdx_path)[0], None)}


def link_spdx2(graph, links, variant_dir):
    """Add placeholder documents for the image SPDX documents and the
    relationships to them; returns the external document info for
    CoreSerializer2."""
    external_docs = {}
    targets = {}
    for element, rel_type, image, kind, package in links:
        doc_name = f"{image}-{kind}"
        if doc_name not in targets:
            spdx_path = os.path.join(variant_dir, image, f"{kind}.spdx")
            targets[doc_name] = None
            if not os.path.isfile(spdx_path):
                print(f"warning: {spdx_path} not found, not linking", file=sys.stderr)
                continue
            graph.add_document(SBOMDocument(name=doc_name, namespace=read_namespace(spdx_path)))
            targets[doc_name] = SBOMComponent(name=f"{doc_name}-{package}")
            graph.add_component(targets[doc_name], doc_name)
            external_docs[doc_name] = (get_hashes(spdx_path)[0], f"SPDXRef-{package}")
        if targets[doc_name]:
            graph.add_relationship(element, targets[doc_name], rel_type)
    return external_docs


def sysbuild_images(variant_dir):
    """Images other than the loader with SPDX documents, as generated by
    extra/build.sh for sysbuild (e.g. 'mcuboot')."""
    if not os.path.isdir(variant_dir):
        return []
    return sorted(
        d for d in os.listdir(variant_dir)
        if d != "loader"
        and os.path.isfile(os.path.join(variant_dir, d, "app.spdx"))
    )


def shared_variant_dirs():
    """Directories in variants/ shared by all variants, as listed in the
    common package contents."""
    with open(os.path.join(REPO_DIR, "extra", "artifacts", "_common.inc")) as f:
        entries = [line.split("#")[0].strip().rstrip("/") for line in f]
    return {e.split("/", 1)[1] for e in entries if e.startswith("variants/")}


def api_blob_info():
    module_yml = os.path.join(REPO_DIR, "zephyr", "module.yml")
    with open(module_yml) as f:
        meta = yaml.safe_load(f)
    for blob in meta.get("blobs", []):
        if blob.get("path", "").startswith("ArduinoCore-API/"):
            return blob
    return {}


def inherit_unit_licenses(component):
    """Files in a library or variant without licensing info of their own
    (examples, metadata, configuration...) get the license of that unit, when
    all of its tagged files share the same one."""
    units = {}
    for f in component.files.values():
        m = re.match(r"(libraries|variants)/[^/]+/", f.relative_path)
        if m and os.path.basename(f.path) != "LICENSE":
            units.setdefault(m.group(0), []).append(f)

    for unit, files in sorted(units.items()):
        untagged = [f for f in files if f.concluded_license == "NOASSERTION"]
        if not untagged:
            continue
        # only the unit's own files count, not the bundled examples
        licenses = {
            f.concluded_license
            for f in files
            if f.license_info_in_file and not re.match(r"[^/]+/[^/]+/(examples|extras)/", f.relative_path)
        }
        if len(licenses) != 1:
            print(f"warning: no single license for {unit}, {len(untagged)} files left as NOASSERTION", file=sys.stderr)
            continue
        (license,) = licenses
        for f in untagged:
            f.concluded_license = license

    lics_concluded, _ = get_component_licenses(component)
    component.concluded_license = normalize_expression(lics_concluded)


def generate_core(root, variant, args, namespace_prefix):
    """Write the core SPDX document of a variant, from the core package
    extracted to root."""
    graph = SBOMGraph(namespace_prefix=namespace_prefix)
    core_version = read_property(os.path.join(root, "platform.txt"), "version")
    graph.metadata["creator_organization"] = SUPPLIER
    graph.metadata["tool_name"] = "ArduinoCore-zephyr gen_core_spdx"
    graph.metadata["tool_version"] = core_version

    doc = SBOMDocument(name="core", title="ArduinoCore-zephyr")
    graph.add_document(doc)

    core = SBOMComponent(
        name="ArduinoCore-zephyr",
        purpose=ComponentPurpose.SOURCE,
        version=core_version,
        url=CORE_URL,
        base_dir=root,
        supplier=SUPPLIER,
    )
    # package URLs: the core package, and its parts for the variant
    core_purl = CORE_PURL
    if core_version:
        core_purl += "@" + urllib.parse.quote(core_version, safe="")
    core.add_external_reference(core_purl)
    graph.add_component(core, doc.name)
    doc.add_described_component(core)

    blob = api_blob_info()
    api = SBOMComponent(
        name="ArduinoCore-API",
        purpose=ComponentPurpose.LIBRARY,
        version=str(blob.get("version", "")),
        url=blob.get("url", ""),
        base_dir=root,
        declared_license=API_LICENSE,
        supplier=SUPPLIER,
    )
    if api.version:
        api.add_external_reference(f"pkg:github/arduino/ArduinoCore-API@{api.version}")
    graph.add_component(api, doc.name)
    graph.add_relationship(core, api, RelationshipType.CONTAINS)

    # variant firmware and EDK packages
    variants_dir = os.path.join(root, "variants")
    other_variants = set(os.listdir(variants_dir)) - shared_variant_dirs() - {variant}
    # links to the image documents:
    # (element, relationship, image, document, target package)
    links = []

    fw = SBOMComponent(
        name=f"{variant}-firmware",
        purpose=ComponentPurpose.APPLICATION,
        version=core_version,
        base_dir=root,
        supplier=SUPPLIER,
        comment=f"Loader firmware for {variant}",
    )
    fw.add_external_reference(f"{core_purl}?variant={urllib.parse.quote(variant, safe='')}")
    graph.add_component(fw, doc.name)
    graph.add_relationship(core, fw, RelationshipType.CONTAINS)

    edk = SBOMComponent(
        name=f"{variant}-llext-edk",
        purpose=ComponentPurpose.SOURCE,
        version=core_version,
        supplier=SUPPLIER,
        comment=f"LLEXT EDK for {variant}: headers exported from the loader build, with comments stripped",
    )
    edk.add_external_reference(f"{core_purl}#variants/{variant}/llext-edk")
    graph.add_component(edk, doc.name)
    graph.add_relationship(core, edk, RelationshipType.CONTAINS)
    links.append((edk, RelationshipType.GENERATED_FROM, "loader", "zephyr", "zephyr-sources"))

    # the other sysbuild images (e.g. the bootloader), packaged if shipped
    output_dir = os.path.join(args.spdx_dir, variant)
    image_packages = {}
    for image in sysbuild_images(output_dir):
        package = SBOMComponent(
            name=f"{variant}-{image}",
            purpose=ComponentPurpose.APPLICATION,
            version=core_version,
            base_dir=root,
            supplier=SUPPLIER,
            comment=f"{image} image for {variant}",
        )
        qualifiers = urllib.parse.urlencode({"image": image, "variant": variant}, quote_via=urllib.parse.quote)
        package.add_external_reference(f"{core_purl}?{qualifiers}")
        image_packages[image] = package

    # assign each file in the archive to its component
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames.sort()
        rel_dir = os.path.relpath(dirpath, root)
        parts = rel_dir.split(os.sep)
        if len(parts) >= 2 and parts[0] == "variants" and parts[1] in other_variants:
            dirnames.clear()  # another variant
            continue
        if len(parts) >= 3 and parts[0] == "variants" and parts[2] == "llext-edk":
            dirnames.clear()  # summarized in the EDK package
            continue
        for filename in sorted(filenames):
            path = os.path.join(dirpath, filename)
            rel_path = os.path.relpath(path, root)
            if rel_path == "REUSE.toml":
                continue  # copied for the scan, not part of the package
            component = core
            source_image = None  # image the file is a build output of
            if rel_path.startswith(API_DIR):
                component = api
            elif m := re.match(r"firmwares/([^-]+)-(.+)\.[^.]+$", rel_path):
                image, file_variant = m.groups()
                if file_variant != variant:
                    continue  # another variant
                if image == "zephyr":
                    component, source_image = fw, "loader"
                elif image in image_packages:
                    component, source_image = image_packages[image], image
                    if not component.files:
                        graph.add_component(component, doc.name)
                        graph.add_relationship(core, component, RelationshipType.CONTAINS)
            sbom_file = SBOMFile(path=path)
            graph.add_file(sbom_file, component)
            if source_image:
                links.append((sbom_file, RelationshipType.GENERATED_FROM, source_image, "app", "app-sources"))

    scan_sbom_graph(ScannerConfig(), graph)
    inherit_unit_licenses(core)

    # the firmware needs the other sysbuild images shipped with it
    for package in image_packages.values():
        if package.files:
            graph.add_relationship(fw, package, RelationshipType.HAS_PREREQUISITE)

    os.makedirs(output_dir, exist_ok=True)
    external_docs = link_spdx2(graph, links, output_dir)
    # the firmware files that are copies of the built images
    copies = {}
    for image, package in [("loader", fw), *image_packages.items()]:
        image_copies, copy_docs = link_copies(
            graph, doc, package.files.values(), os.path.join(output_dir, image, "build.spdx"), f"{image}-build"
        )
        copies.update(image_copies)
        external_docs.update(copy_docs)
    serializer = CoreSerializer2(graph, parse_spdx_version(SPDX_VERSION), external_docs, copies)
    if not serializer.serialize(output_dir):
        sys.exit("failed to write core SPDX document")
    print(f"Wrote {os.path.join(output_dir, 'core.spdx')}")


def main():
    parser = argparse.ArgumentParser(description="Generate the SPDX 2.3 documents for a core package archive.")
    parser.add_argument("archive", help="core package archive (.tar.bz2)")
    parser.add_argument("spdx_dir", help="SPDX directory, with <variant>/loader/ documents from west spdx")
    parser.add_argument("variants", nargs="+", metavar="variant", help="variant to describe")
    parser.add_argument("-n", "--namespace-prefix", help="namespace prefix")
    args = parser.parse_args()

    with tempfile.TemporaryDirectory() as tmpdir:
        with tarfile.open(args.archive) as tar:
            tar.extractall(tmpdir, filter="data")
        root = os.path.join(tmpdir, CORE_ROOT)
        if not os.path.isdir(root):
            sys.exit(f"'{CORE_ROOT}/' not found in {args.archive}")
        for variant in args.variants:
            if not os.path.isdir(os.path.join(root, "variants", variant, "llext-edk")):
                sys.exit(f"variant '{variant}' not found in {args.archive}")

        # annotations for files that cannot carry SPDX tags (not listed)
        shutil.copy(os.path.join(REPO_DIR, "REUSE.toml"), root)

        for variant in args.variants:
            if args.namespace_prefix:
                namespace_prefix = f"{args.namespace_prefix.rstrip('/')}/{variant}"
            else:
                namespace_prefix = f"http://spdx.org/spdxdocs/arduinocore-zephyr-{uuid.uuid4()}"
            generate_core(root, variant, args, namespace_prefix)


if __name__ == "__main__":
    main()
