#!/usr/bin/env python

# Copyright (c) Arduino s.r.l. and/or its affiliated companies
# SPDX-License-Identifier: Apache-2.0

# List the files an image is built from, using the SPDX 2.3 documents
# generated by 'west spdx' for it (e.g. spdx/<variant>/loader, see
# extra/build.sh).
#
# Starting from the final image, the static links are followed to every
# library linked into it, and the files each of them is generated from are
# collected. Each file is printed with the package it belongs to: the
# '-sources' packages hold the files checked out in the workspace, the others
# the files generated during the build. Headers are only listed if 'west spdx'
# was run with --analyze-includes. When a package records its directory in
# the west workspace (PackageFileName), its files are printed with their
# workspace path.

import argparse
import collections
import glob
import json
import os
import posixpath
import sys

FINAL_IMAGE_PACKAGE = "zephyr_final"


def parse_document(path):
    """Parse an SPDX 2 tag-value document into its namespace, external
    document references, elements and relationships."""
    doc = {"namespace": "", "refs": {}, "elements": {}, "relationships": []}
    package = None
    element = None
    with open(path) as f:
        lines = iter(f)
        for line in lines:
            tag, sep, value = line.rstrip("\n").partition(": ")
            if not sep:
                continue
            if value.startswith("<text>"):
                # multi-line text values are not needed: skip them
                while "</text>" not in value:
                    value = next(lines, "</text>")
                continue
            if tag == "DocumentNamespace":
                doc["namespace"] = value
            elif tag == "ExternalDocumentRef":
                ref, namespace, _ = value.split(" ", 2)
                doc["refs"][ref] = namespace
            elif tag == "PackageName":
                element = {"kind": "package", "name": value, "file_name": None}
                package = element
            elif tag == "FileName":
                element = {"kind": "file", "name": value, "package": package}
            elif tag == "SPDXID" and element is not None:
                element["id"] = value
                doc["elements"][value] = element
            elif tag == "PackageFileName" and element is package and element is not None:
                element["file_name"] = value
            elif tag == "Relationship":
                parts = value.split()
                if len(parts) == 3:
                    doc["relationships"].append(tuple(parts))
    return doc


def load_documents(image_dir):
    """Elements and relationships of all documents, keyed by
    (document namespace, SPDX ID)."""
    docs = [parse_document(p) for p in sorted(glob.glob(os.path.join(image_dir, "*.spdx")))]
    elements = {}
    targets = collections.defaultdict(list)  # (from, type) -> [to]

    for doc in docs:
        def key(ref, doc=doc):
            if ":" in ref:
                doc_ref, spdx_id = ref.split(":", 1)
                return doc["refs"].get(doc_ref, doc_ref), spdx_id
            return doc["namespace"], ref

        for spdx_id, element in doc["elements"].items():
            elements[(doc["namespace"], spdx_id)] = element
        for from_ref, rel_type, to_ref in doc["relationships"]:
            targets[(key(from_ref), rel_type)].append(key(to_ref))
    return elements, targets


def workspace_path(package, name):
    """Workspace path of a file of the package, if the package records it."""
    if package and package.get("file_name"):
        return posixpath.normpath(posixpath.join(package["file_name"], name))
    return None


def image_files(image_dir):
    """Return [(package name, file name, workspace path or None)] of the files
    the image is built from."""
    elements, targets = load_documents(image_dir)
    finals = [e for e in elements.values() if e["kind"] == "package" and e["name"] == FINAL_IMAGE_PACKAGE]
    if not finals:
        sys.exit(f"no '{FINAL_IMAGE_PACKAGE}' package found: is this a 'west spdx' SPDX 2 image directory?")

    # artifacts in the image: the files of the final image and everything
    # statically linked into them, recursively
    todo = [k for k, e in elements.items() if e["kind"] == "file" and e["package"] in finals]
    artifacts = set()
    while todo:
        artifact = todo.pop()
        if artifact in artifacts:
            continue
        artifacts.add(artifact)
        todo += targets[(artifact, "STATIC_LINK")]

    files = set()
    for artifact in artifacts:
        files |= {s for s in targets[(artifact, "GENERATED_FROM")] if elements.get(s, {}).get("kind") == "file"}

    result = []
    for f in files:
        element = elements[f]
        package = element["package"] or {}
        name = element["name"].removeprefix("./")
        result.append((package.get("name", ""), name, workspace_path(package, name)))
    return sorted(result)


def main():
    parser = argparse.ArgumentParser(description="List the files an image is built from, from its SPDX 2 documents.")
    parser.add_argument("image_dir", help="directory with the image SPDX 2 documents (e.g. spdx/<variant>/loader)")
    parser.add_argument("--sources-only", action="store_true", help="only list files of '-sources' packages")
    parser.add_argument("--json", action="store_true", help="print a JSON list of {package, file, path}")
    args = parser.parse_args()

    files = image_files(args.image_dir)
    if args.sources_only:
        files = [f for f in files if f[0].endswith("-sources")]

    if args.json:
        json.dump(
            [{"package": package, "file": name, "path": path} for package, name, path in files],
            sys.stdout,
            indent=2,
        )
        print()
    else:
        for package, name, path in files:
            print(f"{package}\t{path or name}")


if __name__ == "__main__":
    main()
