name=PDM
version=1.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Enables the communication with devices that use the PDM Bus
paragraph=
category=Communication
url=
architectures=zephyr_main
includes=PDM.h
