CONFIG_MCUBOOT_LOG_LEVEL_DBG=y
CONFIG_MCUBOOT_DOWNGRADE_PREVENTION=y
CONFIG_BOOT_RSA_PSA=y
CONFIG_BOOT_SIGNATURE_TYPE_RSA=y

# required by 'west spdx' SBOM generation
CONFIG_BUILD_OUTPUT_META=y

# Enable the following parameter to see mcuboot logs
# CONFIG_SERIAL=y
# CONFIG_CONSOLE=y
# CONFIG_UART_CONSOLE=y
