/*
 * Copyright 2023 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_IMX8QM_PINCTRL_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_IMX8QM_PINCTRL_H_

/* values for pad field */
#define SC_P_UART0_RTS_B 23
#define SC_P_UART0_CTS_B 24
#define SC_P_SAI1_RXD 128
#define SC_P_SAI1_TXC 130
#define SC_P_SAI1_TXD 131
#define SC_P_SAI1_TXFS 132

/* mux values */
#define IMX8QM_DMA_LPUART2_RX_UART0_RTS_B 2
#define IMX8QM_DMA_LPUART2_TX_UART0_CTS_B 2
#define IMX8QM_AUD_SAI1_RXD_SAI1_RXD 0
#define IMX8QM_AUD_SAI1_TXC_SAI1_TXC 0
#define IMX8QM_AUD_SAI1_TXD_SAI1_TXD 0
#define IMX8QM_AUD_SAI1_TXFS_SAI1_TXFS 0

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_PINCTRL_IMX8QM_PINCTRL_H_ */
